### ISSUE TITLE
Value function replay and pixel control not uses LSTM context - why?

### ISSUE THREAD

**Issue by Kismuz** [miyosuda/unreal#17]
@miyosuda , thank you for your code!
One point is unclear to me:
when calculating value function replay you always resetting LSTM state, thus assuming it is always 'start of the episode'.
 In `model.py`, lines 229-249:
```
  def _create_vr_network(self):
    # State (Image input)
    self.vr_input = tf.placeholder("float", [None, 84, 84, 3])

    # Last action and reward
    self.vr_last_action_reward_input = tf.placeholder("float", [None, self._action_size+1])

    # VR conv layers
    vr_conv_output = self._base_conv_layers(self.vr_input, reuse=True)

    # pc lastm layers
    vr_initial_lstm_state = self.lstm_cell.zero_state(1, tf.float32)
    # (Initial state is always resetted.)
    
    vr_lstm_outputs, _ = self._base_lstm_layer(vr_conv_output,
                                               self.vr_last_action_reward_input,
                                               vr_initial_lstm_state,
                                               reuse=True)
    # value output
    self.vr_v  = self._base_value_layer(vr_lstm_outputs, reuse=True)
```

Isn't it be correct to store context LSTM state in replay buffer frame and pass it along with state and action-reward inputs?
Added: Same question applies to 'pixel control' estimation.

**Comment by TCherici** [comment]
I may be wrong, but as I understand it the `vr_initial_lstm_state` is only intialized to 0 at the creation of the network. 

Nonetheless, the internal state remains dependent on the last batch used for value replay, while the new batch is completely unrelated on a temporal level. Thus I still think that saving the lstm internal state in the replay buffer and pass it along at the start of each batch is a better solution.

**Comment by Kismuz** [comment]
@TheTazza,
agreed, I'd say it is the only correct solution. I've corrected @miyosuda code in a way mentioned and it indeed gives a gain in performance.

**Comment by miyosuda** [comment]
Thank you for pointing out and sorry for the long delay in reply.

As @Kismuz says, LSTM state is always reset, because there is no LSTM state input in feed here

https://github.com/miyosuda/unreal/blob/31d4886149412fa248f6efa490ab65bd2f425cde/train/trainer.py#L381-L385

While base A3C part has LSTM state feed here,

https://github.com/miyosuda/unreal/blob/31d4886149412fa248f6efa490ab65bd2f425cde/train/trainer.py#L360

so LSTM state for base A3C is dependent on the last batch, but VR LSTM state is always reset to zero now.

And I understand @Kismuz 's suggestion.
First I thought that old LSTM state stored in replay buffer does not match the latest LSTM network weights. However the size of the replay buffer is small, so there won't be big mismatch between stored LSTM state and current network weights. So it will work.

Thank you for the suggestion. And I'm curious about the gain in the performance. Was it a huge gain?

**Comment by Kismuz** [comment]
@miyosuda, first let me thank you for your great work on implementation of Unreal.

> And I'm curious about the gain in the performance. Was it a huge gain?

No, not huge at all and it depends on domain. When resetting LSTM state before processing VR, we basically say 'this is first rollout of the episode', so no prior context is available;  it's ok for domains like ATARi, where agent's behaviour is homogeneous at the duration of entire episode, but if the agent should somehow be sensitive to in-episode dynamics, providing [outdated, as you correctly mentioned] RNN context, to my understanding, is better than flat initial one.

Yet another minor point I should mention, is in implementation of reward prediction:

https://github.com/miyosuda/unreal/blob/31d4886149412fa248f6efa490ab65bd2f425cde/train/experience.py#L113

 - when performing sampling, there is no any checks preventing terminal frame appearing inside four successive frames, which can, while statistically insignificant, add some noise to to RP estimations.

**Comment by miyosuda** [comment]
@Kismuz 

> but if the agent should somehow be sensitive to in-episode dynamics, providing [outdated, as you correctly mentioned] RNN context, to my understanding, is better than flat initial one.

Thank you for the explanation. I understand.

> when performing sampling, there is no any checks preventing terminal frame appearing inside four successive frames, which can, while statistically insignificant, add some noise to to RP estimations.

Ah, I see! You are right. Thank you for pointing this out too.
